//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.530
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.1.
// 
namespace SystemSharp.Interop.Xilinx.PerfCache {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DeviceCache.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("devices", Namespace="http://tempuri.org/DeviceCache.xsd", IsNullable=false)]
    public partial class DeviceRecords {
        
        private DeviceRecordsDevice[] deviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device")]
        public DeviceRecordsDevice[] device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DeviceCache.xsd")]
    public partial class DeviceRecordsDevice {
        
        private string nameField;
        
        private DeviceRecordsDeviceResource[] providedResourcesField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("resource", IsNullable=false)]
        public DeviceRecordsDeviceResource[] providedResources {
            get {
                return this.providedResourcesField;
            }
            set {
                this.providedResourcesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DeviceCache.xsd")]
    public partial class DeviceRecordsDeviceResource {
        
        private string nameField;
        
        private int amountField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
}
