//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.530
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.1.
// 
namespace SystemSharp.Interop.Xilinx.PerfCache {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/IPCoreCache.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("core", Namespace="http://tempuri.org/IPCoreCache.xsd", IsNullable=false)]
    public partial class IPCore {
        
        private string classNameField;
        
        private string generatorField;
        
        private IPCoreVariant[] variantsField;
        
        /// <remarks/>
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        public string generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("variant", IsNullable=false)]
        public IPCoreVariant[] variants {
            get {
                return this.variantsField;
            }
            set {
                this.variantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/IPCoreCache.xsd")]
    public partial class IPCoreVariant {
        
        private string deviceNameField;
        
        private string packageField;
        
        private string speedGradeField;
        
        private string iseVersionField;
        
        private System.DateTime timestampField;
        
        private IPCoreVariantParam[] parametersField;
        
        private IPCoreVariantResource[] consumedResourcesField;
        
        private double minPeriodField;
        
        /// <remarks/>
        public string deviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
            }
        }
        
        /// <remarks/>
        public string package {
            get {
                return this.packageField;
            }
            set {
                this.packageField = value;
            }
        }
        
        /// <remarks/>
        public string speedGrade {
            get {
                return this.speedGradeField;
            }
            set {
                this.speedGradeField = value;
            }
        }
        
        /// <remarks/>
        public string iseVersion {
            get {
                return this.iseVersionField;
            }
            set {
                this.iseVersionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("param", IsNullable=false)]
        public IPCoreVariantParam[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("resource", IsNullable=false)]
        public IPCoreVariantResource[] consumedResources {
            get {
                return this.consumedResourcesField;
            }
            set {
                this.consumedResourcesField = value;
            }
        }
        
        /// <remarks/>
        public double minPeriod {
            get {
                return this.minPeriodField;
            }
            set {
                this.minPeriodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/IPCoreCache.xsd")]
    public partial class IPCoreVariantParam {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/IPCoreCache.xsd")]
    public partial class IPCoreVariantResource {
        
        private string nameField;
        
        private int amountField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
}
